export const lessonsList = [
  { value: "english", label: "Англійська" },
  { value: "spanish", label: "Іспанська" },
  { value: "french", label: "Французька" },
  { value: "german", label: "Німецька" },
  { value: "japanese", label: "Японська" },
  { value: "italian", label: "Італійська" },
  { value: "korean", label: "Корейська" },
  { value: "arabic", label: "Арабська" },
  { value: "chinese", label: "Китайська" },
  { value: "computer", label: "Інформатика" },
  { value: "portuguese", label: "Португальська" },
  { value: "accounting", label: "Бухгалтерський облік" },
  { value: "math", label: "Математика" },
  { value: "statistics", label: "Статистика" },
  { value: "economics", label: "Економіка" },
  { value: "chemistry", label: "Хімія" },
  { value: "biology", label: "Біологія" },
  { value: "algebra", label: "Алгебра" },
  { value: "physics", label: "Фізика" },
  { value: "history", label: "Історія" },
  { value: "russian", label: "Російська" },
  { value: "polish", label: "Польська" },
  { value: "turkish", label: "Турецька" },
  { value: "dutch", label: "Голандська" },
  { value: "ukrainian", label: "Українська" },
  { value: "swedish", label: "Шведська" },
  { value: "hebrew", label: "Іврит" },
  { value: "georgian", label: "Грузинська" },
  { value: "armenian", label: "Вірменська" },
  { value: "norwegian", label: "Норвезька" },
  { value: "hungarian", label: "Угорська" },
  { value: "hindi", label: "Хінді" },
  { value: "greek", label: "Грецька" },
  { value: "czech", label: "Чеська" },
  { value: "finnish", label: "Фінська" },
  { value: "arts", label: "Мистецтво" },
  { value: "music", label: "Музика" },
  { value: "acting", label: "Акторська майстерність" },
  { value: "painting", label: "Живопис" },
  { value: "icelandic", label: "Ісландська" },
  { value: "latin", label: "Латинь" },
  { value: "thai", label: "Тайська" },
  { value: "irish", label: "Ірландська" },
  { value: "romanian", label: "Румунська" },
  { value: "tagalog", label: "Тагальська" },
  { value: "lithuanian", label: "Литовська" },
  { value: "slovak", label: "Словацька" },
  { value: "vietnamese", label: "В'єтнамська" },
  { value: "telugu", label: "Телугу" },
  { value: "tamil", label: "Тамільська" },
  { value: "khmer", label: "Кхмерська" },
  { value: "belarusian", label: "Білоруська" },
  { value: "urdu", label: "Урду" },
  { value: "serbian", label: "Сербська" },
  { value: "bengali", label: "Бенгалі" },
  { value: "bulgarian", label: "Болгарська" },
  { value: "catalan", label: "Каталанська" },
  { value: "sanskrit", label: "Санскрит" },
  { value: "tibetan", label: "Тибетська" },
  { value: "danish", label: "Датська" },
  { value: "sign", label: "Жестова" },
  { value: "croatian", label: "Хорватська" },
  { value: "golang", label: "Go language" },
  { value: "csharp", label: "С#" },
  { value: "corporatefinance", label: "Корпоративне фінансування" },
  { value: "geography", label: "Географія" },
  { value: "philosophy", label: "Філософія" },
  { value: "writing", label: "Письмо" },
  { value: "sociology", label: "Соціологія" },
  { value: "psychology", label: "Психологія" },
  { value: "social", label: "Суспільствознавство" },
  { value: "graphicdesign", label: "Графічний дизайн" },
  { value: "motiondesign", label: "Motion design" },
  { value: "photography", label: "Фотографія" },
  { value: "rlanguage", label: "R" },
  { value: "ppc", label: "PPC" },
  { value: "geometry", label: "Геометрія" },
  { value: "literature", label: "Література" },
  { value: "3ddesign", label: "3D дизайн" },
  { value: "videopostproduction", label: "Відео post-production" },
  { value: "tests", label: "Тести" },
  { value: "law", label: "Юридична справа" },
  { value: "indonesian", label: "Індонезійська" },
  { value: "sales", label: "Продажі" },
  { value: "businessmodelling", label: "Бізнес моделювання" },
  { value: "productmanagement", label: "Управління продуктом" },
  { value: "businessstrategy", label: "Бізнес стратегія" },
  { value: "businessanalytics", label: "Бізнес аналітика" },
  { value: "publicspeaking", label: "Ораторське мистецтво" },
  { value: "html", label: "html" },
  { value: "css", label: "css" },
  { value: "seo", label: "SEO" },
  { value: "smm", label: "SMM" },
  { value: "copywriting", label: "Копірайтинг" },
  { value: "email_marketing", label: "Email маркетинг" },
  { value: "pr", label: "PR" },
  { value: "internationalbusiness", label: "Міжнародний бізнес" },
  { value: "marketingstrategy", label: "Маркетингові стратегії" },
  { value: "contentmarketing", label: "Контент маркетинг" },
  { value: "business", label: "Бізнес і управління" },
  { value: "dota", label: "Dota 2" },
  { value: "concursos", label: "Конкурсний іспит" },
  { value: "objectivec", label: "Objective C" },
  { value: "data_science", label: "Data Science" },
  { value: "uxui", label: "UX/UI" },
  { value: "projectmanagement", label: "Управління IT проектами" },
  { value: "artificialintelligence", label: "Штучний інтелект" },
  { value: "webdevelopment", label: "Веб розробка" },
  { value: "webanalytics", label: "Веб аналітика" },
  { value: "java", label: "Java" },
  { value: "javaScript", label: "java script (js)" },
  { value: "c", label: "C" },
  { value: "swift", label: "Swift" },
  { value: "cplusplus", label: "С++" },
  { value: "rust", label: "Rust" },
]

export const lessonsList1 = ["a", "aa", "aaa", "aaaa"]
